package fin.av.thesis.DAL.Enum;

public enum HealthCondition {
    NONE,
    //Arthritis
    OSTEOARTHRITIS,
    FIBROMYALGIA,
    RHEUMATOID_ARTHRITIS,
    ASTHMA,
    //Cancer
    BLADDER_CANCER,
    BREAST_CANCER,
    CERVICAL_CANCER,
    COLON_CANCER,
    COLORECTAL_CANCER,
    ENDOMETRIAL_CANCER,
    KIDNEY_CANCER,
    LEUKEMIA,
    LIVER_CANCER,
    LUNG_CANCER,
    MULTIPLE_MYELOMA,
    ORAL_CANCER,
    OVARIAN_CANCER,
    PANCREATIC_CANCER,
    SKIN_CANCER,
    STOMACH_CANCER,
    TESTICULAR_CANCER,
    THYROID_CANCER,
    //**************
    CELIAC_DISEASE,
    CHRONIC_FATIGUE_SYNDROME,
    DEPRESSION,
    DIABETES,
    INSULIN_RESISTANCE,
    HEART_ISSUES,
    HIV,
    //Liver health conditions
    HEPATITIS_A,
    HEPATITIS_B,
    HEPATITIS_C,
    HEPATITIS_D,
    HEPATITIS_E,
    CIRRHOSIS,
    FATTY_LIVER_DISEASE,
    PRIMARY_BILIARY_CHOLANGITIS,
    HEPATIC_ENCEPHALOPATHY,
    //**************************
    //Pancreas health conditions
    ACUTE_PANCREATITIS,
    CHRONIC_PANCREATITIS,
    PANCREATIC_CYSTS,
    PANCREATIC_INSUFFICIENCY,
    PANCREATIC_PSEUDOCYST,
    ISLET_CELL_TUMOR,
    PANCREATIC_DIVISUM,
    ZOLLINGER_ELLISON_SYNDROME,
    //*****************************
    //Kidney health conditions
    CHRONIC_KIDNEY_DISEASE,
    ACUTE_KIDNEY_INJURY,
    KIDNEY_STONES,
    POLYCYSTIC_KIDNEY_DISEASE,
    GLOMERULONEPHRITIS,
    NEPHROTIC_SYNDROME,
    RENAL_TUBULAR_ACIDOSIS,
    INTERSTITIAL_NEPHRITIS,
    KIDNEY_INFECTION,
    //********************************
    //Colon health conditions
    CROHNS_DISEASE,
    ULCERATIVE_COLITIS,
    DIVERTICULITIS,
    DIVERTICULOSIS,
    COLON_POLYPS,
    IRRITABLE_BOWEL_SYNDROME,
    ISCHEMIC_COLITIS,
    PSEUDOMEMBRANOUS_COLITIS,
    COLONIC_DYSSYNERGIA,
    //Heart and Circulatory System
    CORONARY_ARTERY_DISEASE,
    HEART_ATTACK,
    CONGESTIVE_HEART_FAILURE,
    ARRHYTHMIA,
    PERIPHERAL_ARTERY_DISEASE,
    HYPERTENSION,

    //Respiratory System
    CHRONIC_OBSTRUCTIVE_PULMONARY_DISEASE,
    PNEUMONIA,
    TUBERCULOSIS,
    PULMONARY_HYPERTENSION,

    //Endocrine System
    DIABETES_MELLITUS_TYPE_1,
    DIABETES_MELLITUS_TYPE_2,
    HYPER_AND_HYPO_THYROIDISM,
    CUSHING_SYNDROME,
    ADDISON_DISEASE,

//Musculoskeletal System
    OSTEOPOROSIS,
    OSTEOPENIA,
    MUSCULAR_DYSTROPHIES,
    GOUT,

//Nervous System
    EPILEPSY,
    MIGRAINE,
    PERIPHERAL_NEUROPATHY,

//Digestive System
    GASTROESOPHAGEAL_REFLUX_DISEASE,
    PEPTIC_ULCER_DISEASE,
    GASTRITIS,
    HEPATIC_STEATOSIS,

//Skin Conditions
    ECZEMA,
    PSORIASIS,
    ACNE
}